# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sign-In-Up' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'SnapKit', '~> 5.6.0'
  # Pods for Sign-In-Up

  target 'Sign-In-UpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Sign-In-UpUITests' do
    # Pods for testing
  end

end

